name: MS Teams Deploy Card

on:
  push:
    branches:    
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      # this is the new step
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.AZURE_FUNCION_TRIGGER }}&commit=${{ github.sha }}"
          method: 'GET' 
          timeout: 1800000


